//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilytechLab.GuitarStringTensionCalculator.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLocalization() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LilytechLab.GuitarStringTensionCalculator.Resources.Localization.AppLocalization", typeof(AppLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The file is corrupted and unreadable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileIsCorrupted {
            get {
                return ResourceManager.GetString("FileIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gauge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Gauge {
            get {
                return ResourceManager.GetString("Gauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High String Length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighStringLength {
            get {
                return ResourceManager.GetString("HighStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lilytech Lab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LilytechLab {
            get {
                return ResourceManager.GetString("LilytechLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low String Length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LowStringLength {
            get {
                return ResourceManager.GetString("LowStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi Scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MultiScale {
            get {
                return ResourceManager.GetString("MultiScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Neck Length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NeckLength {
            get {
                return ResourceManager.GetString("NeckLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Neck Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NeckType {
            get {
                return ResourceManager.GetString("NeckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NeckTypeMulti {
            get {
                return ResourceManager.GetString("NeckTypeMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NeckTypeNormal {
            get {
                return ResourceManager.GetString("NeckTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale Length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScaleLength {
            get {
                return ResourceManager.GetString("ScaleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringCount {
            get {
                return ResourceManager.GetString("StringCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tension {
            get {
                return ResourceManager.GetString("Tension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   th に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th {
            get {
                return ResourceManager.GetString("Th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tuning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tuning {
            get {
                return ResourceManager.GetString("Tuning", resourceCulture);
            }
        }
    }
}
